Try fix.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -69,9 +69,12 @@ jobs:
           choco install -y pkgconfiglite --pre --ignore-checksums --no-progress || (
               sleep 10 &&
               choco install -y pkgconfiglite --pre --ignore-checksums --no-progress || (
-                  echo "Installation failed. Dumping Chocolatey log:" &&
-                  type C:\ProgramData\chocolatey\logs\chocolatey.log &&
-                  exit 1
+                  echo "Installation failed. Retrying with specific version..." &&
+                  choco install -y pkgconfiglite --version=0.9.0 --ignore-checksums --no-progress || (
+                      echo "Installation failed. Dumping Chocolatey log:" &&
+                      type C:\ProgramData\chocolatey\logs\chocolatey.log &&
+                      exit 1
+                  )
               )
           )
           choco upgrade gcc mingw --no-progress
