Try fix.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -65,15 +65,16 @@ jobs:
       - name: Install system dependencies (Windows)
         if: runner.os == 'Windows'
         run: |
-          choco upgrade chocolatey
-          choco install -y pkgconfiglite --pre --ignore-checksums || (
+          choco upgrade chocolatey --no-progress
+          choco install -y pkgconfiglite --pre --ignore-checksums --no-progress || (
               sleep 10 &&
-              choco install -y pkgconfiglite --pre --ignore-checksums || (
+              choco install -y pkgconfiglite --pre --ignore-checksums --no-progress || (
+                  echo "Installation failed. Dumping Chocolatey log:" &&
                   type C:\ProgramData\chocolatey\logs\chocolatey.log &&
                   exit 1
               )
           )
-          choco upgrade gcc mingw
+          choco upgrade gcc mingw --no-progress
 
       - uses: r-lib/actions/setup-r@v2
         with:
